### ISSUE TITLE
Investigate globally ignored emojis

### ISSUE THREAD

**Issue by mario** [mario/Emoji#6]
const ignore = ["1F926", "1F937", "1F938", "1F93C", "1F93D", "1F93E", "1F939"];

**Comment by mario** [comment]
Why are they ignored?

**Comment by vanniktech** [comment]
I think some emojis are duplicated.

**Comment by rubengees** [comment]
Exactly what @vanniktech said, these are flags I think which would show up twice otherwise. The downside of simplify ignoring them though is, that a pasted emoji with that unicode won't be recognized.

**Comment by mario** [comment]
Hm, is there a way to make sure pasted ones work while they're not doubled in the emoji keyboard?

**Comment by vanniktech** [comment]
Yeah we probably need to extend the Emoji class with a list of unicodes that are supported.

**Comment by mario** [comment]
PR in progress, so closing here.
