### ISSUE TITLE
Some emojis are not visible

### ISSUE THREAD

**Issue by mario** [mario/Emoji#9]
According to Google and the defaults in the lib, background is grey. This causes problems when emojis are also grey (i.e. grey square)

**Comment by mario** [comment]
I know about the customizable background, but I guess the defaults should be sane like you said.

Let me open this ticket in your repo.

**Comment by vanniktech** [comment]
You can also leave this issue here and contribute a PR there. Whatever way you want.

**Comment by mario** [comment]
PR opened.
